export const ROLE = {
  ADMIN: "Admin",
  FINANCE: "Finance Manager",
  OPERATIONS: "Operations Manager",
  STAFF: "Staff",
};

export const demoAccounts = [
  {
    id: "USR-001",
    name: "Preeti Admin",
    email: "admin@chatru.com",
    password: "admin123",
    role: ROLE.ADMIN,
    status: "Active",
    avatar: "PA",
  },
  {
    id: "USR-002",
    name: "Rhea Finance",
    email: "finance@chatru.com",
    password: "finance123",
    role: ROLE.FINANCE,
    status: "Active",
    avatar: "RF",
  },
  {
    id: "USR-003",
    name: "Kabir Ops",
    email: "ops@chatru.com",
    password: "ops123",
    role: ROLE.OPERATIONS,
    status: "Active",
    avatar: "KO",
  },
  {
    id: "USR-004",
    name: "Aarav Staff",
    email: "staff@chatru.com",
    password: "staff123",
    role: ROLE.STAFF,
    status: "Active",
    avatar: "AS",
  },
];

export const modules = [
  {
    key: "finance-dashboard",
    label: "Finance",
    icon: "WalletCards",
    roles: [ROLE.ADMIN, ROLE.FINANCE],
    type: "dashboard",
  },
  {
    key: "operations-dashboard",
    label: "Operations",
    icon: "Factory",
    roles: [ROLE.ADMIN, ROLE.OPERATIONS],
    type: "dashboard",
  },
  {
    key: "employees",
    label: "Employees",
    icon: "UsersRound",
    roles: [ROLE.ADMIN, ROLE.OPERATIONS],
    type: "table",
  },
  {
    key: "inventory",
    label: "Inventory",
    icon: "PackageSearch",
    roles: [ROLE.ADMIN, ROLE.OPERATIONS, ROLE.STAFF],
    type: "table",
  },
  {
    key: "vendors",
    label: "Vendors",
    icon: "Handshake",
    roles: [ROLE.ADMIN, ROLE.OPERATIONS, ROLE.FINANCE],
    type: "table",
  },
  {
    key: "sales",
    label: "Sales",
    icon: "ReceiptIndianRupee",
    roles: [ROLE.ADMIN, ROLE.FINANCE, ROLE.STAFF],
    type: "table",
  },
  {
    key: "expenses",
    label: "Expenses",
    icon: "BadgeIndianRupee",
    roles: [ROLE.ADMIN, ROLE.FINANCE],
    type: "table",
  },
  {
    key: "categories",
    label: "Categories",
    icon: "Tags",
    roles: [ROLE.ADMIN, ROLE.FINANCE, ROLE.OPERATIONS],
    type: "table",
  },
  {
    key: "users",
    label: "Users",
    icon: "ShieldCheck",
    roles: [ROLE.ADMIN],
    type: "table",
  },
];

export const tableMeta = {
  employees: {
    title: "Employees",
    subtitle: "People, teams, payroll, and attendance status",
    addLabel: "Add Employee",
    columns: [
      { key: "id", label: "ID" },
      { key: "name", label: "Name" },
      { key: "department", label: "Department" },
      { key: "role", label: "Role" },
      { key: "manager", label: "Manager" },
      { key: "payroll", label: "Payroll" },
      { key: "status", label: "Status" },
    ],
    formFields: [
      "name",
      "department",
      "role",
      "manager",
      "payroll",
      "status",
    ],
  },
  inventory: {
    title: "Inventory",
    subtitle: "Stock levels, locations, and reorder risk",
    addLabel: "Add Item",
    columns: [
      { key: "sku", label: "SKU" },
      { key: "item", label: "Item" },
      { key: "category", label: "Category" },
      { key: "stock", label: "Stock" },
      { key: "reorder", label: "Reorder" },
      { key: "location", label: "Location" },
      { key: "status", label: "Status" },
    ],
    formFields: ["item", "category", "stock", "reorder", "location", "status"],
  },
  vendors: {
    title: "Vendors",
    subtitle: "Suppliers, spend, ratings, and payment state",
    addLabel: "Add Vendor",
    columns: [
      { key: "id", label: "ID" },
      { key: "name", label: "Vendor" },
      { key: "category", label: "Category" },
      { key: "outstanding", label: "Outstanding" },
      { key: "rating", label: "Rating" },
      { key: "status", label: "Status" },
    ],
    formFields: ["name", "category", "outstanding", "rating", "status"],
  },
  sales: {
    title: "Sales",
    subtitle: "Orders, channels, revenue, and collection state",
    addLabel: "Add Sale",
    columns: [
      { key: "order", label: "Order" },
      { key: "customer", label: "Customer" },
      { key: "channel", label: "Channel" },
      { key: "amount", label: "Amount" },
      { key: "date", label: "Date" },
      { key: "status", label: "Status" },
    ],
    formFields: ["customer", "channel", "amount", "date", "status"],
  },
  expenses: {
    title: "Expenses",
    subtitle: "Spend requests, approvals, and monthly cost control",
    addLabel: "Add Expense",
    columns: [
      { key: "id", label: "ID" },
      { key: "category", label: "Category" },
      { key: "owner", label: "Owner" },
      { key: "amount", label: "Amount" },
      { key: "date", label: "Date" },
      { key: "status", label: "Status" },
    ],
    formFields: ["category", "owner", "amount", "date", "status"],
  },
  categories: {
    title: "Categories",
    subtitle: "Shared classification for finance and operations",
    addLabel: "Add Category",
    columns: [
      { key: "id", label: "ID" },
      { key: "name", label: "Name" },
      { key: "type", label: "Type" },
      { key: "owner", label: "Owner" },
      { key: "budget", label: "Budget" },
      { key: "status", label: "Status" },
    ],
    formFields: ["name", "type", "owner", "budget", "status"],
  },
  users: {
    title: "Users",
    subtitle: "Access, roles, and activity",
    addLabel: "Add User",
    columns: [
      { key: "id", label: "ID" },
      { key: "name", label: "Name" },
      { key: "email", label: "Email" },
      { key: "role", label: "Role" },
      { key: "lastLogin", label: "Last Login" },
      { key: "status", label: "Status" },
    ],
    formFields: ["name", "email", "role", "lastLogin", "status"],
  },
};

export const initialData = {
  employees: [
    {
      id: "EMP-101",
      name: "Meera Sharma",
      department: "Finance",
      role: "Accounts Lead",
      manager: "Preeti Admin",
      payroll: "Rs 82,000",
      status: "Active",
    },
    {
      id: "EMP-102",
      name: "Rohan Gupta",
      department: "Operations",
      role: "Warehouse Lead",
      manager: "Kabir Ops",
      payroll: "Rs 74,000",
      status: "Active",
    },
    {
      id: "EMP-103",
      name: "Isha Verma",
      department: "Sales",
      role: "Key Accounts",
      manager: "Preeti Admin",
      payroll: "Rs 68,000",
      status: "On Leave",
    },
    {
      id: "EMP-104",
      name: "Nitin Rao",
      department: "Procurement",
      role: "Buyer",
      manager: "Kabir Ops",
      payroll: "Rs 61,000",
      status: "Active",
    },
  ],
  inventory: [
    {
      sku: "SKU-CH-400",
      item: "Copper Wire Roll",
      category: "Raw Material",
      stock: "420",
      reorder: "120",
      location: "Delhi WH",
      status: "Healthy",
    },
    {
      sku: "SKU-CH-512",
      item: "Control Panel Kit",
      category: "Assembly",
      stock: "48",
      reorder: "60",
      location: "Noida WH",
      status: "Low",
    },
    {
      sku: "SKU-CH-629",
      item: "Safety Gloves",
      category: "Consumable",
      stock: "900",
      reorder: "200",
      location: "Jaipur WH",
      status: "Healthy",
    },
    {
      sku: "SKU-CH-710",
      item: "Bearing Set",
      category: "Spares",
      stock: "22",
      reorder: "50",
      location: "Delhi WH",
      status: "Critical",
    },
  ],
  vendors: [
    {
      id: "VEN-201",
      name: "Ananta Metals",
      category: "Raw Material",
      outstanding: "Rs 4.2L",
      rating: "4.7",
      status: "Preferred",
    },
    {
      id: "VEN-202",
      name: "BlueKart Logistics",
      category: "Transport",
      outstanding: "Rs 1.1L",
      rating: "4.4",
      status: "Active",
    },
    {
      id: "VEN-203",
      name: "NorthStar Tools",
      category: "Equipment",
      outstanding: "Rs 80K",
      rating: "4.1",
      status: "Review",
    },
    {
      id: "VEN-204",
      name: "Apex Packaging",
      category: "Packaging",
      outstanding: "Rs 2.6L",
      rating: "4.8",
      status: "Preferred",
    },
  ],
  sales: [
    {
      order: "ORD-9001",
      customer: "Kundan Electricals",
      channel: "Direct",
      amount: "Rs 8.7L",
      date: "2026-07-02",
      status: "Paid",
    },
    {
      order: "ORD-9002",
      customer: "Metro Infra",
      channel: "Distributor",
      amount: "Rs 12.4L",
      date: "2026-07-06",
      status: "Pending",
    },
    {
      order: "ORD-9003",
      customer: "Prime Buildcon",
      channel: "Direct",
      amount: "Rs 5.1L",
      date: "2026-07-11",
      status: "Paid",
    },
    {
      order: "ORD-9004",
      customer: "Eastern Mills",
      channel: "Marketplace",
      amount: "Rs 3.9L",
      date: "2026-07-13",
      status: "Overdue",
    },
  ],
  expenses: [
    {
      id: "EXP-310",
      category: "Logistics",
      owner: "Kabir Ops",
      amount: "Rs 1.8L",
      date: "2026-07-03",
      status: "Approved",
    },
    {
      id: "EXP-311",
      category: "Utilities",
      owner: "Rhea Finance",
      amount: "Rs 74K",
      date: "2026-07-05",
      status: "Approved",
    },
    {
      id: "EXP-312",
      category: "Maintenance",
      owner: "Rohan Gupta",
      amount: "Rs 92K",
      date: "2026-07-12",
      status: "Pending",
    },
    {
      id: "EXP-313",
      category: "Travel",
      owner: "Isha Verma",
      amount: "Rs 38K",
      date: "2026-07-14",
      status: "Review",
    },
  ],
  categories: [
    {
      id: "CAT-01",
      name: "Raw Material",
      type: "Inventory",
      owner: "Operations",
      budget: "Rs 22L",
      status: "Active",
    },
    {
      id: "CAT-02",
      name: "Logistics",
      type: "Expense",
      owner: "Finance",
      budget: "Rs 8L",
      status: "Active",
    },
    {
      id: "CAT-03",
      name: "Direct Sales",
      type: "Revenue",
      owner: "Sales",
      budget: "Rs 40L",
      status: "Active",
    },
    {
      id: "CAT-04",
      name: "Maintenance",
      type: "Expense",
      owner: "Operations",
      budget: "Rs 5L",
      status: "Review",
    },
  ],
  users: [
    {
      id: "USR-001",
      name: "Preeti Admin",
      email: "admin@chatru.com",
      role: ROLE.ADMIN,
      lastLogin: "Today, 09:20",
      status: "Active",
    },
    {
      id: "USR-002",
      name: "Rhea Finance",
      email: "finance@chatru.com",
      role: ROLE.FINANCE,
      lastLogin: "Today, 08:47",
      status: "Active",
    },
    {
      id: "USR-003",
      name: "Kabir Ops",
      email: "ops@chatru.com",
      role: ROLE.OPERATIONS,
      lastLogin: "Yesterday, 18:31",
      status: "Active",
    },
    {
      id: "USR-004",
      name: "Aarav Staff",
      email: "staff@chatru.com",
      role: ROLE.STAFF,
      lastLogin: "Yesterday, 16:12",
      status: "Limited",
    },
  ],
};
